#pragma checksum "..\..\WallSplitter\MaterialAssignWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F478FFE6621CC9D377A4B29E2FBC980DBBEAC4FD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WallSplitter {
    
    
    /// <summary>
    /// MaterialAssignWindow
    /// </summary>
    public partial class MaterialAssignWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 18 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl MainTabControl;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FilterTargetCombo;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FilterBox;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FilterModeCombo;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SelectAllButton;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SelectNoneButton;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MaterialFilterBox;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox MaterialCombo;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedMaterialText;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition TypeNameColumn;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition CurrentMaterialColumn;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition NewMaterialColumn;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter TypeNameSplitter;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter CurrentMaterialSplitter;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ItemsPanel;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CountText;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PendingChangesText;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DelFilterBox;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox DelFilterModeCombo;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DelSelectAllButton;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DelSelectNoneButton;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DelItemsPanel;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DelCountText;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox IdFilterBox;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox IdFilterModeCombo;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button IdSelectAllButton;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button IdSelectNoneButton;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox IdTargetFieldCombo;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox IdNewValueBox;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition IdNameColumn;
        
        #line default
        #line hidden
        
        
        #line 218 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition IdClassColumn;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition IdDescriptionColumn;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter IdNameSplitter;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter IdClassSplitter;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel IdItemsPanel;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock IdCountText;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\WallSplitter\MaterialAssignWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock IdPendingChangesText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WallSplitter;component/materialassignwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MainTabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 2:
            this.FilterTargetCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 35 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.FilterTargetCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.FilterTargetCombo_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.FilterBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 40 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.FilterBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.FilterBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.FilterModeCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 41 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.FilterModeCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.FilterModeCombo_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.SelectAllButton = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.SelectAllButton.Click += new System.Windows.RoutedEventHandler(this.SelectAllButton_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.SelectNoneButton = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.SelectNoneButton.Click += new System.Windows.RoutedEventHandler(this.SelectNoneButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.MaterialFilterBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 58 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.MaterialFilterBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.MaterialFilterBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.MaterialCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 59 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.MaterialCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.MaterialCombo_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.SelectedMaterialText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.TypeNameColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 11:
            this.CurrentMaterialColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 12:
            this.NewMaterialColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 13:
            this.TypeNameSplitter = ((System.Windows.Controls.GridSplitter)(target));
            
            #line 84 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.TypeNameSplitter.DragDelta += new System.Windows.Controls.Primitives.DragDeltaEventHandler(this.ColumnSplitter_DragDelta);
            
            #line default
            #line hidden
            return;
            case 14:
            this.CurrentMaterialSplitter = ((System.Windows.Controls.GridSplitter)(target));
            
            #line 87 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.CurrentMaterialSplitter.DragDelta += new System.Windows.Controls.Primitives.DragDeltaEventHandler(this.ColumnSplitter_DragDelta);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ItemsPanel = ((System.Windows.Controls.StackPanel)(target));
            
            #line 93 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.ItemsPanel.MouseMove += new System.Windows.Input.MouseEventHandler(this.ItemsPanel_MouseMove);
            
            #line default
            #line hidden
            
            #line 94 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.ItemsPanel.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.ItemsPanel_MouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 95 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.ItemsPanel.LostMouseCapture += new System.Windows.Input.MouseEventHandler(this.ItemsPanel_LostMouseCapture);
            
            #line default
            #line hidden
            return;
            case 16:
            this.CountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.PendingChangesText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            
            #line 106 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelButton_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 107 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ApplyButton_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 108 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FinalApplyButton_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.DelFilterBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 128 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelFilterBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.DelFilterBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 22:
            this.DelFilterModeCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 129 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelFilterModeCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DelFilterModeCombo_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 23:
            this.DelSelectAllButton = ((System.Windows.Controls.Button)(target));
            
            #line 137 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelSelectAllButton.Click += new System.Windows.RoutedEventHandler(this.DelSelectAllButton_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.DelSelectNoneButton = ((System.Windows.Controls.Button)(target));
            
            #line 138 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelSelectNoneButton.Click += new System.Windows.RoutedEventHandler(this.DelSelectNoneButton_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.DelItemsPanel = ((System.Windows.Controls.StackPanel)(target));
            
            #line 145 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelItemsPanel.MouseMove += new System.Windows.Input.MouseEventHandler(this.DelItemsPanel_MouseMove);
            
            #line default
            #line hidden
            
            #line 146 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelItemsPanel.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.DelItemsPanel_MouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 147 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.DelItemsPanel.LostMouseCapture += new System.Windows.Input.MouseEventHandler(this.DelItemsPanel_LostMouseCapture);
            
            #line default
            #line hidden
            return;
            case 26:
            this.DelCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            
            #line 156 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelButton_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            
            #line 157 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteButton_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.IdFilterBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 178 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdFilterBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.IdFilterBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 30:
            this.IdFilterModeCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 179 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdFilterModeCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.IdFilterModeCombo_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 31:
            this.IdSelectAllButton = ((System.Windows.Controls.Button)(target));
            
            #line 187 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdSelectAllButton.Click += new System.Windows.RoutedEventHandler(this.IdSelectAllButton_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.IdSelectNoneButton = ((System.Windows.Controls.Button)(target));
            
            #line 188 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdSelectNoneButton.Click += new System.Windows.RoutedEventHandler(this.IdSelectNoneButton_Click);
            
            #line default
            #line hidden
            return;
            case 33:
            this.IdTargetFieldCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 196 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdTargetFieldCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.IdTargetFieldCombo_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 34:
            this.IdNewValueBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 201 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdNewValueBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.IdNewValueBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 35:
            this.IdNameColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 36:
            this.IdClassColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 37:
            this.IdDescriptionColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 38:
            this.IdNameSplitter = ((System.Windows.Controls.GridSplitter)(target));
            
            #line 224 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdNameSplitter.DragDelta += new System.Windows.Controls.Primitives.DragDeltaEventHandler(this.IdColumnSplitter_DragDelta);
            
            #line default
            #line hidden
            return;
            case 39:
            this.IdClassSplitter = ((System.Windows.Controls.GridSplitter)(target));
            
            #line 227 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdClassSplitter.DragDelta += new System.Windows.Controls.Primitives.DragDeltaEventHandler(this.IdColumnSplitter_DragDelta);
            
            #line default
            #line hidden
            return;
            case 40:
            this.IdItemsPanel = ((System.Windows.Controls.StackPanel)(target));
            
            #line 233 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdItemsPanel.MouseMove += new System.Windows.Input.MouseEventHandler(this.IdItemsPanel_MouseMove);
            
            #line default
            #line hidden
            
            #line 234 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdItemsPanel.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.IdItemsPanel_MouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 235 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            this.IdItemsPanel.LostMouseCapture += new System.Windows.Input.MouseEventHandler(this.IdItemsPanel_LostMouseCapture);
            
            #line default
            #line hidden
            return;
            case 41:
            this.IdCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.IdPendingChangesText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            
            #line 246 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelButton_Click);
            
            #line default
            #line hidden
            return;
            case 44:
            
            #line 247 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.IdApplyButton_Click);
            
            #line default
            #line hidden
            return;
            case 45:
            
            #line 248 "..\..\WallSplitter\MaterialAssignWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.IdFinalApplyButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

