#pragma checksum "..\..\WallSplitter\PatternStudioWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "01E4C6C558E41A2A8BCA0A0D02EA5B1CDCFFD88B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WallSplitter {
    
    
    /// <summary>
    /// PatternStudioWindow
    /// </summary>
    public partial class PatternStudioWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 101 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SourceComboBox;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PatternTypeText;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SourceUnitText;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox GridList;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas PreviewCanvas;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ShowOriginalCheckBox;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EmptyPreviewText;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OverallAngleBox;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider OverallAngleSlider;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UniformScaleBox;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider UniformScaleSlider;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox WidthBox;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider WidthSlider;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HeightBox;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider HeightSlider;
        
        #line default
        #line hidden
        
        
        #line 200 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LockAxesCheckBox;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReferenceAxisText;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedGridText;
        
        #line default
        #line hidden
        
        
        #line 211 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GroupAngleBox;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GroupAngleSlider;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GroupSizeBox;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GroupSizeSlider;
        
        #line default
        #line hidden
        
        
        #line 227 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GroupSpacingBox;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GroupSpacingSlider;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SaveNameBox;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox OverwriteCheckBox;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 256 "..\..\WallSplitter\PatternStudioWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveToRevitButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WallSplitter;component/patternstudiowindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\WallSplitter\PatternStudioWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SourceComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 101 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.SourceComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SourceComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 102 "..\..\WallSplitter\PatternStudioWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenPatButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 103 "..\..\WallSplitter\PatternStudioWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ResetAllButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PatternTypeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.SourceUnitText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.GridList = ((System.Windows.Controls.ListBox)(target));
            
            #line 127 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GridList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GridList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PreviewCanvas = ((System.Windows.Controls.Canvas)(target));
            
            #line 145 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.PreviewCanvas.SizeChanged += new System.Windows.SizeChangedEventHandler(this.PreviewCanvas_SizeChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ShowOriginalCheckBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 149 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.ShowOriginalCheckBox.Checked += new System.Windows.RoutedEventHandler(this.PreviewOption_Changed);
            
            #line default
            #line hidden
            
            #line 149 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.ShowOriginalCheckBox.Unchecked += new System.Windows.RoutedEventHandler(this.PreviewOption_Changed);
            
            #line default
            #line hidden
            return;
            case 9:
            this.EmptyPreviewText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.OverallAngleBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 173 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.OverallAngleBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 173 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.OverallAngleBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 11:
            this.OverallAngleSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 174 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.OverallAngleSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.OverallAngleSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.UniformScaleBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 181 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.UniformScaleBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 181 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.UniformScaleBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 13:
            this.UniformScaleSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 182 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.UniformScaleSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.UniformScaleSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.WidthBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 189 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.WidthBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 189 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.WidthBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 15:
            this.WidthSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 190 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.WidthSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.WidthSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.HeightBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 197 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.HeightBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 197 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.HeightBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 17:
            this.HeightSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 198 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.HeightSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.HeightSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.LockAxesCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.ReferenceAxisText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.SelectedGridText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.GroupAngleBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 211 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupAngleBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 211 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupAngleBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 22:
            this.GroupAngleSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 212 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupAngleSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GroupAngleSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 23:
            this.GroupSizeBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 219 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupSizeBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 219 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupSizeBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 24:
            this.GroupSizeSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 220 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupSizeSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GroupSizeSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 25:
            this.GroupSpacingBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 227 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupSpacingBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NumericBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 227 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupSpacingBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NumericBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 26:
            this.GroupSpacingSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 228 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.GroupSpacingSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GroupSpacingSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 230 "..\..\WallSplitter\PatternStudioWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ResetSelectedGridButton_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.SaveNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.OverwriteCheckBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 252 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.OverwriteCheckBox.Checked += new System.Windows.RoutedEventHandler(this.OverwriteCheckBox_Changed);
            
            #line default
            #line hidden
            
            #line 252 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.OverwriteCheckBox.Unchecked += new System.Windows.RoutedEventHandler(this.OverwriteCheckBox_Changed);
            
            #line default
            #line hidden
            return;
            case 30:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            
            #line 254 "..\..\WallSplitter\PatternStudioWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ExportPatButton_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            
            #line 255 "..\..\WallSplitter\PatternStudioWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelButton_Click);
            
            #line default
            #line hidden
            return;
            case 33:
            this.SaveToRevitButton = ((System.Windows.Controls.Button)(target));
            
            #line 256 "..\..\WallSplitter\PatternStudioWindow.xaml"
            this.SaveToRevitButton.Click += new System.Windows.RoutedEventHandler(this.SaveToRevitButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

