#pragma checksum "..\..\..\WallSplitter\PatternPunchWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4C144311EBDF72DAB3C2230D522E6F3E02CBFD94"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WallSplitter {
    
    
    internal partial class PatternPunchWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 40 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PatternNameText;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PatternInfoText;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectionStateText;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox TargetList;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl PreviewTabs;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas SelectionCanvas;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas FullCanvas;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox MinimumSizeCheckBox;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MinimumWidthBox;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MinimumHeightBox;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CountText;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ComplexityText;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ValidateButton;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ValidationText;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RunButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WallSplitter;component/patternpunchwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.PatternNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.PatternInfoText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.SelectionStateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TargetList = ((System.Windows.Controls.ListBox)(target));
            
            #line 66 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.TargetList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TargetList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.PreviewTabs = ((System.Windows.Controls.TabControl)(target));
            
            #line 83 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.PreviewTabs.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PreviewTabs_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.SelectionCanvas = ((System.Windows.Controls.Canvas)(target));
            
            #line 87 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.SelectionCanvas.SizeChanged += new System.Windows.SizeChangedEventHandler(this.PreviewCanvas_SizeChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.FullCanvas = ((System.Windows.Controls.Canvas)(target));
            
            #line 97 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.FullCanvas.SizeChanged += new System.Windows.SizeChangedEventHandler(this.PreviewCanvas_SizeChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.MinimumSizeCheckBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 114 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.MinimumSizeCheckBox.Checked += new System.Windows.RoutedEventHandler(this.Option_Changed);
            
            #line default
            #line hidden
            
            #line 114 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.MinimumSizeCheckBox.Unchecked += new System.Windows.RoutedEventHandler(this.Option_Changed);
            
            #line default
            #line hidden
            return;
            case 9:
            this.MinimumWidthBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 128 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.MinimumWidthBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Option_Changed);
            
            #line default
            #line hidden
            return;
            case 10:
            this.MinimumHeightBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 132 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.MinimumHeightBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Option_Changed);
            
            #line default
            #line hidden
            return;
            case 11:
            this.CountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.ComplexityText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.ValidateButton = ((System.Windows.Controls.Button)(target));
            
            #line 143 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.ValidateButton.Click += new System.Windows.RoutedEventHandler(this.ValidateButton_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.ValidationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            
            #line 167 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelButton_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.RunButton = ((System.Windows.Controls.Button)(target));
            
            #line 169 "..\..\..\WallSplitter\PatternPunchWindow.xaml"
            this.RunButton.Click += new System.Windows.RoutedEventHandler(this.RunButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

