using System.Collections;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Autodesk.Revit.DB;
using WallSplitter;
static class Program {
 static readonly BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public;
 static object Get(object o,string n)=>o.GetType().GetField(n,F)!.GetValue(o)!;
 static T Get<T>(object o,string n)=>(T)Get(o,n);
 static object? Call(object o,string n,params object?[] args)=>o.GetType().GetMethods(F).Single(m=>m.Name==n&&m.GetParameters().Length==args.Length).Invoke(o,args);
 static void Check(bool ok,string name){if(!ok)throw new Exception(name);Console.WriteLine("PASS "+name);}
 static List<Element> List(NamerWindow w,string name)=>Get<List<Element>>(w,name);
 static object Row(NamerWindow w,ElementId id)=>Get<IList>(w,"_rows").Cast<object>().Single(r=>Get<ElementId>(r,"ElementId")==id);
 static void Select(NamerWindow w,ElementId id)=>Get<CheckBox>(Row(w,id),"CheckBox").IsChecked=true;
 static void Click(NamerWindow w,string method)=>Call(w,method,w,new RoutedEventArgs());
 static void FamilyMode(NamerWindow w)=>Get<RadioButton>(w,"CategoryFamilyRadio").IsChecked=true;
 [STAThread] static void Main(){
  var app=new Application {ShutdownMode=ShutdownMode.OnExplicitShutdown};
  var d=new Document();
  var a=new Family{Id=new(1),Name="문_자동문"};var b=new Family{Id=new(2),Name="창_고정창"};var empty=new Family{Id=new(3),Name="빈 패밀리"};
  d.Elements.AddRange(new Element[]{a,b,empty});
  for(int i=0;i<245;i++){var t=new FamilySymbol{Id=new(100+i),Name=i==0?"900 x 2100":i==1?"양개형":"유형_"+i.ToString("000"),Family=a};a.Symbols.Add(t.Id);d.Elements.Add(t);}
  var bt=new FamilySymbol{Id=new(500),Name="900 x 2100",Family=b};b.Symbols.Add(bt.Id);d.Elements.Add(bt);
  var w=new NamerWindow(d,new(){a.Id});
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").SetEquals(new[]{a.Id}),"사전 선택은 패밀리만");
  Check(List(w,"_displayElements").Count==3,"처음에는 패밀리만 표시");
  Get<TextBox>(w,"FilterBox").Text="자동문";
  Check(List(w,"_filteredElements").Count==246,"패밀리 검색으로 이름이 다른 유형 245개 포함");
  Check(List(w,"_displayElements").Count==1,"검색된 패밀리는 접힌 상태");
  Click(w,"SelectNoneButton_Click");Click(w,"SelectAllButton_Click");
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").SetEquals(new[]{a.Id}),"전체 선택은 접힌 유형을 새로 선택하지 않음");
  Click(w,"SelectNoneButton_Click");Call(w,"ToggleFamily",a.Id);
  Check(List(w,"_displayElements").Count==246 && Get<IList>(w,"_rows").Count==200,"유형 펼침과 200행 페이징");
  var groups=Get<Dictionary<ElementId,CheckBox>>(w,"_familyTypeChecks");
  Check(groups.Count==1,"펼친 패밀리에만 유형 전체 선택 체크박스");
  groups[a.Id].RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Primitives.ButtonBase.ClickEvent));
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").Count==245 && !Get<HashSet<ElementId>>(w,"_checkedIds").Contains(a.Id),"유형 전체 선택은 부모 제외하고 페이지 밖 유형 포함");
  Get<CheckBox>(Row(w,new(100)),"CheckBox").IsChecked=false;
  Check(groups[a.Id].IsChecked==false && groups[a.Id].Content.ToString()!.Contains("244/245"),"개별 유형 선택 변경과 집계 동기화");
  groups[a.Id].RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Primitives.ButtonBase.ClickEvent));
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").Count==245,"일부 선택에서 클릭하면 전체 선택");
  groups[a.Id].RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Primitives.ButtonBase.ClickEvent));
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").Count==0,"하위 유형 체크박스로 전체 해제");
  Check(Get<NamerWindow.NamerCategory>(Row(w,new(100)),"Category")==NamerWindow.NamerCategory.Type,"하위 유형의 특성 경로");
  Select(w,new(100)); Call(w,"ToggleFamily",a.Id);
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").Contains(new(100)),"접어도 선택 유지");
  Check(Get<TextBlock>(w,"CountText").Text.Contains("접힌 유형 1개"),"접힌 선택 개수 표시");
  Get<RadioButton>(w,"ModeInsertRadio").IsChecked=true;Get<TextBox>(w,"PositionBox").Text="1";Get<TextBox>(w,"InsertTextBox").Text="ST_";
  Click(w,"ApplyButton_Click");
  Check(Get<Dictionary<ElementId,string>>(w,"_workingNames")[new(100)]=="ST_900 x 2100","접힌 선택 유형 일괄 수정");
  Check(!Get<Dictionary<ElementId,string>>(w,"_workingNames").ContainsKey(a.Id)&&a.Name=="문_자동문","부모 이름과 Revit 원본은 그대로");
  Call(w,"ToggleFamily",a.Id);Call(w,"RenderMoreRows");
  Check(Get<IList>(w,"_rows").Count==246,"더 보기로 모든 유형 표시");
  Call(w,"BeginInlineEdit",Row(w,new(101)));Get<TextBox>(Row(w,new(101)),"Editor").Text="사용자 지정 유형";
  Call(w,"ToggleFamily",a.Id);
  Check(Get<Dictionary<ElementId,string>>(w,"_workingNames")[new(101)]=="사용자 지정 유형","접을 때 인라인 편집 확정");
  Get<TextBox>(w,"FilterBox").Text="고정창";
  Check(!Get<HashSet<ElementId>>(w,"_checkedIds").Contains(new(100)),"검색에서 제외된 패밀리의 유형 체크 해제");
  Check(Get<Dictionary<ElementId,string>>(w,"_workingNames").Count==2,"검색 후에도 확정한 편집 유지");
  Click(w,"FinalApplyButton_Click");
  Check(Get<NamerExternalEventHandler>(w,"_handler").PendingRenames!.Count==2,"최종 적용은 누적 편집만 한 번씩 요청");
  Get<RadioButton>(w,"CategoryTypeRadio").IsChecked=true;Get<TextBox>(w,"FilterBox").Text="ST_";
  Check(List(w,"_filteredElements").Count==1,"유형 탭과 작업 이름 공유");
  FamilyMode(w);Get<TextBox>(w,"FilterBox").Text="자동문";Call(w,"ToggleFamily",a.Id);
  Click(w,"SelectAllButton_Click");
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").Count==246,"펼친 전체 선택은 더 보기 뒤 유형도 포함");
  Call(w,"ToggleFamily",a.Id);Click(w,"SelectNoneButton_Click");
  Check(Get<HashSet<ElementId>>(w,"_checkedIds").Count==0,"전체 해제는 접힌 유형도 포함");
  for(int mode=0;mode<6;mode++){
   Get<ComboBox>(w,"FilterModeCombo").SelectedIndex=mode;Get<TextBox>(w,"FilterBox").Text="문_자동문";
   int parents=List(w,"_filteredElements").OfType<Family>().Count();
   Check(parents==(mode==1||mode==3?2:1),"필터 방식 "+mode);
  }
  Get<TextBox>(w,"FilterBox").Text="";Check(List(w,"_filteredElements").OfType<Family>().Count()==3,"빈 필터는 모든 패밀리");
  Get<ComboBox>(w,"FilterModeCombo").SelectedIndex=0;Get<TextBox>(w,"FilterBox").Text="자동문";Call(w,"ToggleFamily",a.Id);
  var content=(System.Windows.Controls.Grid)w.Content;content.Background=(Brush)w.FindResource("WindowBackgroundBrush");content.Measure(new Size(780,640));content.Arrange(new Rect(0,0,780,640));content.UpdateLayout();
  Call(w,"NamerWindow_Loaded",w,new RoutedEventArgs());content.UpdateLayout();
  var bitmap=new RenderTargetBitmap(780,640,96,96,PixelFormats.Pbgra32);bitmap.Render(content);
  var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(bitmap));using(var f=System.IO.File.Create("namer-hierarchy.png"))png.Save(f);
  Check(Get<TextBlock>(w,"FamilyHierarchyHint").ActualHeight>0,"패밀리 안내문 표시");
  Check(NamerWindow.CollectCandidates(d,NamerWindow.NamerCategory.Family).Count==3,"공유 패밀리 수집 계약 유지");
  var childRow=Row(w,new(101));var parentRow=Row(w,a.Id);
  Check(Math.Abs(Get<System.Windows.Controls.Grid>(childRow,"OldNameHost").Width+44-Get<System.Windows.Controls.Grid>(parentRow,"OldNameHost").Width-28)<0.01,"부모/자식 이름 열 너비 정렬");
  var props=Get<Button>(childRow,"PropsButton");Call(w,"PropsButton_Click",props,new RoutedEventArgs());
  Check(Get<NamerExternalEventHandler>(w,"_handler").PendingProperties!.Category==NamerWindow.NamerCategory.Type && Get<NamerExternalEventHandler>(w,"_handler").PendingProperties!.Id==new ElementId(101),"유형 특성 요청에 정확한 유형 ID 전달");
  Call(w,"RenderMoreRows");Call(w,"RenderRows",true);
  Check(Get<IList>(w,"_rows").Count==246,"다시 그릴 때 더 보기 분량 유지");
  w.OnRenamesApplied(new NamerCommand.RenameResult{Status=TransactionStatus.RolledBack});
  Check(Get<Dictionary<ElementId,string>>(w,"_workingNames").Count==2,"롤백 시 작업 이름 유지");
  foreach(var pair in Get<Dictionary<ElementId,string>>(w,"_workingNames"))d.GetElement(pair.Key)!.Name=pair.Value;
  w.OnRenamesApplied(new NamerCommand.RenameResult{Status=TransactionStatus.Committed,Renamed=2});
  Check(Get<Dictionary<ElementId,string>>(w,"_workingNames").Count==0 && Get<HashSet<ElementId>>(w,"_expandedFamilies").Contains(a.Id),"성공 후 작업값 정리와 펼침 유지");
  Select(w,a.Id);Select(w,new(101));Get<TextBox>(w,"PositionBox").Text="1";Get<TextBox>(w,"InsertTextBox").Text="NEW_";Click(w,"ApplyButton_Click");
  Check(Get<Dictionary<ElementId,string>>(w,"_workingNames").Count==2 && Get<Dictionary<ElementId,string>>(w,"_workingNames").ContainsKey(a.Id),"부모와 선택 유형 함께 일괄 편집");
  Call(w,"BeginInlineEdit",Row(w,new(101)));Get<TextBox>(Row(w,new(101)),"Editor").Text="다른 문서에 쓰면 안 됨";
  w.UpdateDocumentAndSelection(new Document{PathName="other.rvt",Elements=new(){new Family{Id=new(101),Name="다른 문서 패밀리"}}},new());
  Check(Get<HashSet<ElementId>>(w,"_expandedFamilies").Count==0&&Get<Dictionary<ElementId,string>>(w,"_workingNames").Count==0,"문서 전환 시 상태 격리");
  w.Close();Console.WriteLine("ALL NAMER HIERARCHY TESTS PASSED");
  MaterialTests.Run();
  LayerTests.Run();
 }
}
