<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>WallSplitter</AssemblyName></PropertyGroup><ItemGroup><Compile Include="../../WallSplitter/NamerWindow.xaml.cs" Link="NamerWindow.xaml.cs"/><Compile Include="../../WallSplitter/Theme.cs" Link="Theme.cs"/><Page Include="../../WallSplitter/NamerWindow.xaml" Link="NamerWindow.xaml"/><Page Include="../../WallSplitter/Resources/Theme.xaml" Link="Resources/Theme.xaml"/></ItemGroup></Project>
