#pragma checksum "..\..\QuickToggleToolbar.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CD40AB170764D6D489FF81033F199F37073A0802"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WallSplitter {
    
    
    /// <summary>
    /// QuickToggleToolbar
    /// </summary>
    public partial class QuickToggleToolbar : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 59 "..\..\QuickToggleToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ButtonsPanel;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\QuickToggleToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel RightControlsPanel;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\QuickToggleToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveViewButton;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\QuickToggleToolbar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RevertButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WallSplitter;component/quicktoggletoolbar.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\QuickToggleToolbar.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 48 "..\..\QuickToggleToolbar.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.DragGrip_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ButtonsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            this.RightControlsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.SaveViewButton = ((System.Windows.Controls.Button)(target));
            
            #line 71 "..\..\QuickToggleToolbar.xaml"
            this.SaveViewButton.Click += new System.Windows.RoutedEventHandler(this.SaveViewButton_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.RevertButton = ((System.Windows.Controls.Button)(target));
            
            #line 75 "..\..\QuickToggleToolbar.xaml"
            this.RevertButton.Click += new System.Windows.RoutedEventHandler(this.RevertButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

